import type { Metadata } from 'next';
import '@fontsource-variable/onest';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Protectora-Fido',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang='es'>
      <body className='flex flex-col min-h-screen '>
        <Header />
        <main className='flex-grow '>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
