import type { Metadata } from 'next';
import '@fontsource/lobster';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Protectora-Fido',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang='es'>
      <body className='mt-5'>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
